#!/bin/bash

echo "🔧 Force Camera Permissions Reset for HTTPS"
echo ""
echo "1. Go to Chrome settings:"
echo "   chrome://settings/content/camera"
echo ""
echo "2. Look for these entries and DELETE them:"
echo "   - https://192.168.0.109:5174"
echo "   - http://192.168.0.109:5173"
echo "   - Any 192.168.0.109 entries"
echo ""
echo "3. Do the same for microphone:"
echo "   chrome://settings/content/microphone"
echo ""
echo "4. Clear all site data:"
echo "   chrome://settings/content/all"
echo "   Search: 192.168.0.109"
echo "   Delete all entries"
echo ""
echo "5. Restart Chrome completely:"
echo "   Close all Chrome windows"
echo "   Reopen Chrome"
echo ""
echo "6. Test again:"
echo "   Go to: https://192.168.0.109:5174"
echo "   Try joining class"
echo "   Should now show permission prompt"